[versions]
agp = "9.0.1"
junitJupiterApi = "5.14.3"
kotlin = "2.3.10"
chicory = "999-SNAPSHOT"

[libraries]
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitJupiterApi" }
chicory-wasi = { module = "com.dylibso.chicory:wasi", version.ref = "chicory"}
chicory-runtime = { module = "com.dylibso.chicory:runtime", version.ref = "chicory"}
chicory-wasm = { module = "com.dylibso.chicory:wasm", version.ref = "chicory"}
chicory-wasmCorpus = { module = "com.dylibso.chicory:wasm-corpus", version.ref = "chicory"}
android-gradle-plugin-api = { module = "com.android.tools.build:gradle-api", version.ref = "agp"}
[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-junit5 = { id = "de.mannodermaus.android-junit5", version = "2.0.1"}
